### ISSUE TITLE
OneOf is not Send

### ISSUE THREAD

**Issue by andrew-otiv** [komora-io/terrors#13]
We tried and failed to use OneOf on a separate thread because OneOf types don't appear to be send...

fn foo() -> impl Send {
    OneOf::new(())
}

results in:

error[E0277]: `(dyn Any + 'static)` cannot be sent between threads safely
   --> otiv3/physical_controls/physical_controls.rs:155:13
    |
155 | fn foo() -> impl Send {
    |             ^^^^^^^^^ `(dyn Any + 'static)` cannot be sent between threads safely
    |
    = help: the trait `Send` is not implemented for `(dyn Any + 'static)`, which is required by `OneOf<_>: Send`
    = note: required for `Unique<(dyn Any + 'static)>` to implement `Send`
note: required because it appears within the type `Box<(dyn Any + 'static)>`
   --> /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/alloc/src/boxed.rs:196:12
note: required because it appears within the type `OneOf<_>`
   --> external/otiv3_crate_index__terrors-0.3.0/src/one_of.rs:32:12

Thanks for the interesting library!

**Comment by spacejam** [comment]
This should work now, as of version `0.3.1` ! Thank you for opening this :)
