### ISSUE TITLE
Consider mentioning the license more prominently

### ISSUE THREAD

**Issue by Expurple** [komora-io/terrors#2]
I see that you've set `license = "MIT OR Apache-2.0"` in your `Cargo.toml`. You should also include the `LICENSE` files and mention the license in the README, so that people can confidently experiment with your code. I want to open a pull request, [but I can't be sure if I'm allowed to do that](https://opensource.stackexchange.com/a/1721/26106)

**Comment by spacejam** [comment]
Hey :) Done: https://github.com/komora-io/terrors/commit/6675b701f5f06da312fbd128628cc2a60dbd2edb
