### ISSUE TITLE
Avoid unidiomatic one-element tuples

### ISSUE THREAD

**Issue by Expurple** [komora-io/terrors#8]
Documentation examples and tests contain `OneOf<(T,)>`-shaped return values:

- `fn allocate_box() -> Result<Box<u8>, OneOf<(AllocationFailure,)>>`
- `fn send() -> Result<(), OneOf<(Timeout,)>>`
- `fn allocates() -> Result<(), OneOf<(NotEnoughMemory,)>>`

You can find all of them using this regex: `OneOf<\(\w+,\)>`

I'm heavily against using such examples in documentation. No real-world code looks like this. It's always going to be `Result<_, T>` rather than `Result<_, OneOf<(T,)>>`. The current examples may falsely imply that the library is unergonomic and *requires* returning `OneOf<(T,)>` instead of `T`.

If you want to showcase broadening, I suggest using real-world patterns like `T` -> `OneOf<(T, U)>` or `OneOf<(T, U)>` -> `OneOf<(T, U, V)>`, instead of `OneOf<(T,)>` -> `OneOf<(T, U)>`. In tests, we can keep that case if you want to cover it, but I'd add a comment that it is unidiomatic and simply covers an edge case.

If you agree in principle, let me know and I'll implement these changes myself.

**Comment by spacejam** [comment]
I prefer to keep the examples as simple as possible for now

**Comment by Expurple** [comment]
This is understandable. This means that we shouldn't add `OneOf<(T, U)>` -> `OneOf<(T, U, V)>` examples yet.

But I'd argue that

```rust
fn inner -> Result<T, E1> {
    unimplemented!()
}

fn outer -> Result<T, OneOf<(E1, E2)>> {
    inner().map_err(OneOf::new)
}
```

is actually *simpler* than the current

```rust
fn inner -> Result<T, OneOf<(E1,)>> {
    unimplemented!()
}

fn outer -> Result<T, OneOf<(E1, E2)>> {
    inner().map_err(OneOf::broaden)
}
```

And if you can imagine applying some of these changes in the future, I suggest keeping the issue open for tracking purposes and discussion
